import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "../components/Hero";
import { BlogContainer } from "../components/blogs";
import { GetStaticProps } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home|spoofy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <BlogContainer />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  return {
    props: {
      data: null,
    },
  };
};

export default Home;
